M48
; DRILL file {KiCad (6.99.0-1665-g4ee6cfe5b6)} date Tue Jun 28 13:02:29 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-28T13:02:29+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-1665-g4ee6cfe5b6)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.3551Y-2.7051
X5.3551Y-2.9327
T0
M30
